###################################################################################################
#                                                                                                 #
# This file is part of BLASFEO.                                                                   #
#                                                                                                 #
# BLASFEO -- BLAS For Embedded Optimization.                                                      #
# Copyright (C) 2016-2018 by Gianluca Frison.                                                     #
# Developed at IMTEK (University of Freiburg) under the supervision of Moritz Diehl.              #
# All rights reserved.                                                                            #
#                                                                                                 #
# This program is free software: you can redistribute it and/or modify                            #
# it under the terms of the GNU General Public License as published by                            #
# the Free Software Foundation, either version 3 of the License, or                               #
# (at your option) any later version                                                              #.
#                                                                                                 #
# This program is distributed in the hope that it will be useful,                                 #
# but WITHOUT ANY WARRANTY; without even the implied warranty of                                  #
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the                                   #
# GNU General Public License for more details.                                                    #
#                                                                                                 #
# You should have received a copy of the GNU General Public License                               #
# along with this program.  If not, see <https://www.gnu.org/licenses/>.                          #
#                                                                                                 #
# The authors designate this particular file as subject to the "Classpath" exception              #
# as provided by the authors in the LICENSE file that accompained this code.                      #
#                                                                                                 #
# Author: Gianluca Frison, gianluca.frison (at) imtek.uni-freiburg.de                             #
#                                                                                                 #
###################################################################################################

include ../Makefile.rule

OBJS =

ifeq ($(BLAS_API), 1)

ifeq ($(LA), HIGH_PERFORMANCE)

OBJS += dcopy.o
OBJS += dgemm.o
OBJS += dsyrk.o
OBJS += dtrmm.o
OBJS += dtrsm.o
OBJS += dpotrf.o
OBJS += dpotrs.o
OBJS += dtrtrs.o

#endif # HIGH_PERFROMANCE

else #ifeq ($(LA), REFERENCE)

OBJS += dgemm_ref.o

endif # REFERENCE

endif # BLAS_API

obj: $(OBJS)

clean:
	rm -f *.o
	rm -f *.s

dgemm_ref.o: dgemm_ref.c xgemm_ref.c
