default:
	# create directories
	mkdir -p build


	# compile latex
	pdflatex -output-directory=build guide

	# compile bibliography
	# biber -output-directory=build -input-directory=build guide

	# compile latex
	# pdflatex -output-directory=build guide


# pushd build
# pdflatex $file-frn.tex
# popd

# pdflatex --output-directory=build/ $1
